# Nama Workflow untuk ditampilkan di tab Actions GitHub
name: Build and Deploy StrideBase

# Pemicu (Trigger): Menjalankan workflow setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Menggunakan OS terbaru dari GitHub untuk menjalankan job
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Login ke Docker Hub (atau registry lain)
      # Simpan username dan token di GitHub Secrets (DOCKERHUB_USERNAME, DOCKERHUB_TOKEN)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: indraadwii
          password: dckr_pat_ZH6yrPS-jp8sBJlW2voTLg3yItA

      # Langkah 3: Build dan Push Docker image untuk Server (Backend)
      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server # Path ke folder server
          push: true
          tags: indradwii/stridebase-server:latest

      # Langkah 4: Build dan Push Docker image untuk Client (Frontend)
      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client # Path ke folder client
          push: true
          tags: indradwii/stridebase-client:latest

      # Langkah 5: Deploy ke Server Produksi menggunakan SSH
      # Simpan konfigurasi server di GitHub Secrets (HOST, USERNAME, SSH_KEY)
      # - name: Deploy to production server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       # Pindah ke direktori proyek di server
      #       cd /path/to/your/project/stridebase-app
            
      #       # Tarik versi terbaru dari docker-compose.yml (jika ada perubahan)
      #       git pull origin main
            
      #       # Hentikan container yang sedang berjalan dan jalankan yang baru dengan image terbaru
      #       docker-compose down
      #       docker-compose up -d